import type { Metadata } from "next";
import ReduxProvider from "@/redux/provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "../css/theme.css";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};
import Footer from "@/components/Footer";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const messages = await getMessages();

  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-dvh bg-sol-bg">
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            {/* main flex-grow ensures the footer stays at the bottom */}
            <main className="flex-grow flex flex-col items-center justify-center">
              {children}
            </main>
            <Footer />
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}