import type { Metadata } from "next";
import ReduxProvider from "@/redux/provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "../css/theme.css";
import "katex/dist/katex.min.css";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const messages = await getMessages();

  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/anhoc.svg" />
        <link rel="stylesheet" href="https://tikzjax.com/v1/fonts.css" />
        <script src="https://tikzjax.com/v1/tikzjax.js" async></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  var appThemeRaw = localStorage.getItem('app-theme');
                  var supportDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches === true;
                  if (!theme && supportDarkMode) theme = 'dark';
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                    document.documentElement.setAttribute('data-theme', 'dark');
                  } else {
                    document.documentElement.setAttribute('data-theme', 'light');
                  }

                  if (appThemeRaw) {
                    var appTheme = JSON.parse(appThemeRaw);
                    var variables = theme === 'dark' ? appTheme.dark_variables : appTheme.light_variables;
                    document.documentElement.setAttribute('data-app-theme', appTheme.slug || 'default');
                    if (variables && typeof variables === 'object') {
                      Object.entries(variables).forEach(function(entry) {
                        document.documentElement.style.setProperty(entry[0], entry[1]);
                      });
                    }
                  } else {
                    document.documentElement.setAttribute('data-app-theme', 'default');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="bg-sol-bg h-full">
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
