import type { Metadata } from "next";
import ReduxProvider from "@/redux/provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "../css/theme.css";
import "katex/dist/katex.min.css";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const messages = await getMessages();

  return (
    <html lang="en" className="h-full">
      <body className="bg-sol-bg h-full">
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}