
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.13.0
 * Query Engine version: 361e86d0ea4987e9f53a565309b3eed797a6bcbd
 */
Prisma.prismaVersion = {
  client: "6.13.0",
  engine: "361e86d0ea4987e9f53a565309b3eed797a6bcbd"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  country: 'country',
  password_hash: 'password_hash',
  account_status: 'account_status',
  role_id: 'role_id',
  learn_unit_id: 'learn_unit_id',
  slots_purchased: 'slots_purchased',
  created_at: 'created_at',
  first_name: 'first_name',
  last_name: 'last_name',
  login_id: 'login_id',
  avatar_url: 'avatar_url',
  stripe_customer_id: 'stripe_customer_id',
  active_session_id: 'active_session_id'
};

exports.Prisma.UserSecurityScalarFieldEnum = {
  user_id: 'user_id',
  email_verification_token: 'email_verification_token',
  email_verification_sent_at: 'email_verification_sent_at',
  email_verified_at: 'email_verified_at',
  first_login_at: 'first_login_at',
  inactive_cleanup_at: 'inactive_cleanup_at',
  failed_login_attempts: 'failed_login_attempts',
  lockout_until: 'lockout_until',
  password_reset_token: 'password_reset_token',
  password_reset_sent_at: 'password_reset_sent_at'
};

exports.Prisma.UserLearningProfileScalarFieldEnum = {
  user_id: 'user_id',
  preferred_subject_id: 'preferred_subject_id'
};

exports.Prisma.LearnUnitScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  supervisor_id: 'supervisor_id',
  max_subjects: 'max_subjects',
  max_grades: 'max_grades',
  max_lessons: 'max_lessons',
  max_templates: 'max_templates',
  max_teachers: 'max_teachers',
  max_students: 'max_students',
  created_at: 'created_at'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.ActionScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.ResourceScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  id: 'id',
  role_id: 'role_id',
  action_id: 'action_id',
  resource_id: 'resource_id'
};

exports.Prisma.GradeScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title_en: 'title_en',
  title_vi: 'title_vi',
  subject_id: 'subject_id',
  created_by: 'created_by'
};

exports.Prisma.SubjectScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title_en: 'title_en',
  title_vi: 'title_vi',
  color: 'color',
  is_classified: 'is_classified',
  created_by: 'created_by'
};

exports.Prisma.UserSubjectAccessRequestScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  subject_id: 'subject_id',
  status: 'status',
  requested_at: 'requested_at',
  reviewed_at: 'reviewed_at',
  reviewed_by: 'reviewed_by'
};

exports.Prisma.RoleSubjectPermissionScalarFieldEnum = {
  id: 'id',
  role_id: 'role_id',
  subject_id: 'subject_id'
};

exports.Prisma.LessonScalarFieldEnum = {
  id: 'id',
  grade_id: 'grade_id',
  subject_id: 'subject_id',
  title_en: 'title_en',
  title_vi: 'title_vi',
  content_markdown_en: 'content_markdown_en',
  content_markdown_vi: 'content_markdown_vi',
  order_index: 'order_index',
  created_by: 'created_by',
  is_premium: 'is_premium',
  updated_at: 'updated_at'
};

exports.Prisma.QuestionTemplateScalarFieldEnum = {
  id: 'id',
  lesson_id: 'lesson_id',
  created_by: 'created_by',
  template_type: 'template_type',
  difficulty: 'difficulty',
  is_premium: 'is_premium',
  body_template_en: 'body_template_en',
  body_template_vi: 'body_template_vi',
  explanation_template_en: 'explanation_template_en',
  explanation_template_vi: 'explanation_template_vi',
  logic_config: 'logic_config',
  accepted_formulas: 'accepted_formulas',
  tags: 'tags',
  created_at: 'created_at'
};

exports.Prisma.TestAttemptScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  lesson_id: 'lesson_id',
  total_score: 'total_score',
  is_completed: 'is_completed',
  is_practice: 'is_practice',
  started_at: 'started_at',
  completed_at: 'completed_at'
};

exports.Prisma.QuestionSnapshotScalarFieldEnum = {
  id: 'id',
  attempt_id: 'attempt_id',
  template_id: 'template_id',
  generated_variables: 'generated_variables',
  student_answer: 'student_answer',
  right_answers: 'right_answers',
  is_correct: 'is_correct',
  points_earned: 'points_earned',
  responded_at: 'responded_at'
};

exports.Prisma.QuestionTemplateReportScalarFieldEnum = {
  id: 'id',
  template_id: 'template_id',
  snapshot_id: 'snapshot_id',
  attempt_id: 'attempt_id',
  lesson_id: 'lesson_id',
  reporter_id: 'reporter_id',
  reason: 'reason',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.LearningSessionScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  lesson_id: 'lesson_id',
  started_at: 'started_at',
  ended_at: 'ended_at',
  duration_sec: 'duration_sec'
};

exports.Prisma.UserLessonMasteryScalarFieldEnum = {
  user_id: 'user_id',
  lesson_id: 'lesson_id',
  mastery_score: 'mastery_score',
  total_study_time: 'total_study_time',
  total_test_time: 'total_test_time',
  completion_status: 'completion_status',
  last_activity_at: 'last_activity_at'
};

exports.Prisma.XpLogScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  amount: 'amount',
  reason: 'reason',
  occurred_at: 'occurred_at'
};

exports.Prisma.AchievementScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  theme_id: 'theme_id',
  title_en: 'title_en',
  title_vi: 'title_vi',
  description_en: 'description_en',
  description_vi: 'description_vi',
  category: 'category',
  xp_reward: 'xp_reward',
  icon: 'icon'
};

exports.Prisma.ThemeScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title_en: 'title_en',
  title_vi: 'title_vi',
  description_en: 'description_en',
  description_vi: 'description_vi',
  preview_color: 'preview_color',
  light_variables: 'light_variables',
  dark_variables: 'dark_variables'
};

exports.Prisma.UserAchievementScalarFieldEnum = {
  user_id: 'user_id',
  achievement_id: 'achievement_id',
  earned_at: 'earned_at'
};

exports.Prisma.UserFollowScalarFieldEnum = {
  follower_id: 'follower_id',
  following_id: 'following_id',
  created_at: 'created_at'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  recipient_id: 'recipient_id',
  actor_id: 'actor_id',
  type: 'type',
  entity_type: 'entity_type',
  entity_id: 'entity_id',
  payload: 'payload',
  read_at: 'read_at',
  created_at: 'created_at'
};

exports.Prisma.StudentStatsScalarFieldEnum = {
  user_id: 'user_id',
  lessons_completed: 'lessons_completed',
  total_xp: 'total_xp',
  level: 'level',
  average_score: 'average_score',
  last_active: 'last_active',
  lives: 'lives',
  last_life_restored_at: 'last_life_restored_at',
  coins: 'coins',
  level_points: 'level_points',
  coin_transactions: 'coin_transactions',
  inventory: 'inventory',
  equipped_items: 'equipped_items',
  upgrades: 'upgrades'
};

exports.Prisma.ActivityEvidenceScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  attempt_id: 'attempt_id',
  snapshot_id: 'snapshot_id',
  image_url: 'image_url',
  caption: 'caption',
  uploaded_at: 'uploaded_at'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  event_type: 'event_type',
  metadata: 'metadata',
  occurred_at: 'occurred_at'
};

exports.Prisma.GameChallengeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  game_type: 'game_type',
  grade_id: 'grade_id',
  lesson_id: 'lesson_id',
  created_by: 'created_by',
  is_active: 'is_active',
  created_at: 'created_at',
  config: 'config'
};

exports.Prisma.GameAttemptScalarFieldEnum = {
  id: 'id',
  challenge_id: 'challenge_id',
  user_id: 'user_id',
  guest_name: 'guest_name',
  guest_token: 'guest_token',
  score: 'score',
  time_spent: 'time_spent',
  completed_at: 'completed_at'
};

exports.Prisma.PlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  vi_name: 'vi_name',
  en_name: 'en_name',
  description: 'description',
  price_monthly: 'price_monthly',
  price_annually: 'price_annually',
  max_students: 'max_students',
  max_teachers: 'max_teachers',
  max_lessons: 'max_lessons',
  max_templates: 'max_templates',
  max_subjects: 'max_subjects',
  max_grades: 'max_grades',
  price_per_student_monthly: 'price_per_student_monthly',
  price_per_student_annually: 'price_per_student_annually',
  price_per_teacher_monthly: 'price_per_teacher_monthly',
  price_per_teacher_annually: 'price_per_teacher_annually',
  price_per_lesson_monthly: 'price_per_lesson_monthly',
  price_per_lesson_annually: 'price_per_lesson_annually',
  price_per_grade_monthly: 'price_per_grade_monthly',
  price_per_grade_annually: 'price_per_grade_annually',
  price_per_template_monthly: 'price_per_template_monthly',
  price_per_template_annually: 'price_per_template_annually',
  effect_from: 'effect_from',
  effect_to: 'effect_to',
  created_at: 'created_at'
};

exports.Prisma.SubscriptionPlanScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  plan_id: 'plan_id',
  status: 'status',
  billing_cycle: 'billing_cycle',
  start_date: 'start_date',
  end_date: 'end_date',
  auto_renew: 'auto_renew',
  slots_purchased: 'slots_purchased',
  stripe_subscription_id: 'stripe_subscription_id',
  max_students: 'max_students',
  max_teachers: 'max_teachers',
  max_lessons: 'max_lessons',
  max_templates: 'max_templates',
  max_grades: 'max_grades',
  max_subjects: 'max_subjects',
  effect_from: 'effect_from',
  effect_to: 'effect_to',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  subscription_plan_id: 'subscription_plan_id',
  amount: 'amount',
  billing_date: 'billing_date',
  status: 'status',
  stripe_invoice_id: 'stripe_invoice_id',
  description: 'description',
  created_at: 'created_at'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  user_id: 'user_id',
  expires_at: 'expires_at',
  created_at: 'created_at',
  revoked_at: 'revoked_at'
};

exports.Prisma.OAuthAccountScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  provider: 'provider',
  provider_user_id: 'provider_user_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.UserStreakScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  current_streak: 'current_streak',
  longest_streak: 'longest_streak',
  weekly_streak: 'weekly_streak',
  last_active_date: 'last_active_date',
  streak_start_date: 'streak_start_date',
  missed_days: 'missed_days',
  rewards_generated_at: 'rewards_generated_at',
  precalculated_rewards: 'precalculated_rewards',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.StreakRewardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  reward_type: 'reward_type',
  specific_date: 'specific_date',
  required_days: 'required_days',
  reward_payload: 'reward_payload',
  message_en: 'message_en',
  message_vi: 'message_vi',
  is_repeatable: 'is_repeatable',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.UserStreakRewardClaimScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  streak_reward_id: 'streak_reward_id',
  streak_day: 'streak_day',
  claimed_at: 'claimed_at'
};

exports.Prisma.UserDailyQuestScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  quest_type: 'quest_type',
  target_count: 'target_count',
  current_count: 'current_count',
  xp_reward: 'xp_reward',
  is_completed: 'is_completed',
  date: 'date',
  created_at: 'created_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  User: 'User',
  UserSecurity: 'UserSecurity',
  UserLearningProfile: 'UserLearningProfile',
  LearnUnit: 'LearnUnit',
  Role: 'Role',
  Action: 'Action',
  Resource: 'Resource',
  RolePermission: 'RolePermission',
  Grade: 'Grade',
  Subject: 'Subject',
  UserSubjectAccessRequest: 'UserSubjectAccessRequest',
  RoleSubjectPermission: 'RoleSubjectPermission',
  Lesson: 'Lesson',
  QuestionTemplate: 'QuestionTemplate',
  TestAttempt: 'TestAttempt',
  QuestionSnapshot: 'QuestionSnapshot',
  QuestionTemplateReport: 'QuestionTemplateReport',
  LearningSession: 'LearningSession',
  UserLessonMastery: 'UserLessonMastery',
  XpLog: 'XpLog',
  Achievement: 'Achievement',
  Theme: 'Theme',
  UserAchievement: 'UserAchievement',
  UserFollow: 'UserFollow',
  Notification: 'Notification',
  StudentStats: 'StudentStats',
  ActivityEvidence: 'ActivityEvidence',
  AuditLog: 'AuditLog',
  GameChallenge: 'GameChallenge',
  GameAttempt: 'GameAttempt',
  Plan: 'Plan',
  SubscriptionPlan: 'SubscriptionPlan',
  Invoice: 'Invoice',
  RefreshToken: 'RefreshToken',
  OAuthAccount: 'OAuthAccount',
  UserStreak: 'UserStreak',
  StreakReward: 'StreakReward',
  UserStreakRewardClaim: 'UserStreakRewardClaim',
  UserDailyQuest: 'UserDailyQuest'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
